### ISSUE TITLE
How can I config for FTP upload recorded videos?

### ISSUE THREAD

**Issue by vstevenphan** [EliasKotlyar/Xiaomi-Dafang-Hacks#1111]
I just pasted the mod firmware and run the camera. I do not know how to config the file to let it upload videos to my FTP Server. There is no tutorial to show that. Please help!

**Comment by BozoTClown** [comment]
I am not sure if you have found a solution for this yet or not, but the following is how I FTP my files. One note on storing videos/stills, DO NOT store them on the sd card. This will cause premature failure of the sd card. I learned this the hard way on my Raspberry PI's running motion. After time the constant writes/deletes cause the cards to become corrupt.

/usr/bin/ftpput -v -u username -p password -P 21 servername filename

Hope this helps someone

**Comment by vstevenphan** [comment]
So you use a rasperry pi?

**Comment by BozoTClown** [comment]
That is what I use, but you can use any OS as an FTP server you desire.

**Comment by vstevenphan** [comment]
I mean have already a FTP server. How to upload the videos from the cam to that FTP server. What file can I config?

**Comment by vstevenphan** [comment]
I don't know what file I should put my FTP server info to make the camera upload the videos to my FTP server

**Comment by BozoTClown** [comment]
If you already have an FTP server you should be ready to go. Have you created a FTP user and password on your FTP server? You should also create a default home for the FTP files to copy to.

**Comment by BozoTClown** [comment]
I would manully connect before I try to automate it.

**Comment by vstevenphan** [comment]
I can connect my FTP server to upload files fro WinSCP app

**Comment by vstevenphan** [comment]
My problem is which file I need to config/put my FTP server so that the camera can upload videos to it?

**Comment by BozoTClown** [comment]
What FTP server are you using?

**Comment by vstevenphan** [comment]
cloudbox247 server

**Comment by vstevenphan** [comment]
Here my connection info:

FTP Host: | ftp.cloudbox247.com
-- | --
FTP Login: | thexstay
FTP Password: | *****
My question is, where I put those info into the camera files to make it runs?

**Comment by BozoTClown** [comment]
/usr/bin/ftpput -v -u username -p password -P 21 servername filename

It is all right here

**Comment by vstevenphan** [comment]
Where I put those command?

**Comment by BozoTClown** [comment]
/usr/bin/ftpput -v -u thexstay -p ***** -P 21 ftp.cloudbox247.com filename

**Comment by BozoTClown** [comment]
Run it manually and see if it works, then I will explain what to do after that.

**Comment by vstevenphan** [comment]
Sorry, I misunderstand your point right now. Where can I run the command? My command window from my PC?

**Comment by BozoTClown** [comment]
You will need to ssh into the camera

**Comment by BozoTClown** [comment]
Use putty for that. I am assuming you have already hacked your camera, since this is the Dafang-Hacks blog

**Comment by vstevenphan** [comment]
Yes, I have hack the camera, I'm trying to figure out how to SSH to the camera

**Comment by BozoTClown** [comment]
First do you already have Putty? If not you can download it, it's free. What OS are you operating from?

**Comment by vstevenphan** [comment]
I have downloaded it. I know how to use it as I'm managing a VPS

**Comment by vstevenphan** [comment]
But I don't know how to use it with the camera SSH

**Comment by vstevenphan** [comment]
![image](https://user-images.githubusercontent.com/10742539/65835103-6c717b80-e30c-11e9-839c-b61d86518dc8.png)
How can I get those info?

**Comment by BozoTClown** [comment]
You need to get the IP address of the camera from your router if you don't already know it. Then enter it as the Host Name

**Comment by BozoTClown** [comment]
Then enter a name in the Saved Sessions box and click the save button. After that click the opne button.

**Comment by vstevenphan** [comment]
There are two IP address: 192.168.1.94 

WAN IPv4 Address | 100.97.152.213
-- | --
I use the below address to access my router?

**Comment by BozoTClown** [comment]
Sorry, I did not see your post where you said you know how to use it. The camera is just a Busybox linux OS.

**Comment by BozoTClown** [comment]
192.168.1.94 looks to be an internal address, I would try that one. The username is root and the password is ismart12

**Comment by vstevenphan** [comment]
Yes, it's the internal address, and the above adress: 100.97.152.213 is my current IP address. How can I access the camera? and about the port, is it 22 at all? @@

**Comment by vstevenphan** [comment]
I can access the camera web admin page, but I don't know which info I should out in Putty to run command you provided

**Comment by BozoTClown** [comment]
I am confused, what OS are you chatting from?

**Comment by vstevenphan** [comment]
![image](https://user-images.githubusercontent.com/10742539/65835224-f0783300-e30d-11e9-84cd-c38e4a9716aa.png)

**Comment by vstevenphan** [comment]
I'm using using my PC (Windows) to chat with you right now ?

**Comment by BozoTClown** [comment]
So that tells me the cameras IP is 192.168.1.94

**Comment by vstevenphan** [comment]
Alright. Get into the console right now

**Comment by vstevenphan** [comment]
![image](https://user-images.githubusercontent.com/10742539/65835258-451bae00-e30e-11e9-8a20-99a4d284fd48.png)

**Comment by BozoTClown** [comment]
YEA!!!

**Comment by BozoTClown** [comment]
type "cd /system/sdcard" without the quotes.

**Comment by vstevenphan** [comment]
![image](https://user-images.githubusercontent.com/10742539/65835285-a2176400-e30e-11e9-88f0-690ca387ccdb.png)
done

**Comment by vstevenphan** [comment]
And what's the next?

**Comment by BozoTClown** [comment]
Great, we need to do a couple of things. 
1. Change the root password
2. Create a folder to put script files in
3. Findout where your pictures/videos are being stored.

Have you used Teamviewer before?

**Comment by vstevenphan** [comment]
Ok, 1 267 917 466
hwz752

**Comment by BozoTClown** [comment]
I am back

**Comment by vstevenphan** [comment]
yes, I'm trying to find the problem with the FTP server

**Comment by BozoTClown** [comment]
Which cloud is it?

**Comment by vstevenphan** [comment]
It's a service that a guy recommend me to use ):

**Comment by BozoTClown** [comment]
Which one is it, I will see if I can find anything

**Comment by vstevenphan** [comment]
Well, can we edit the FTP server info. I will use my USB as a NAS to test it?

**Comment by vstevenphan** [comment]
1 267 917 466
hwz752

**Comment by vstevenphan** [comment]
Well, it takes time to setup a new FTP server on my VPS because in that VPS, there are all spaces for my websites already. If you can test on the "USB FTP" first successfully, I will change the FTP info of your script to make it run on my FTP VPS server later @@

**Comment by vstevenphan** [comment]
There is a problem with the recorded videos. All of them are not watchable and in black @@

**Comment by Morphy99** [comment]
@BozoTClown is this still valid? I'm trying to do this but getting

`/usr/bin/ftpput -v -u xxxx -p xxxx -P 21 192.168.xxx.xxx temp.jpg
Connecting to 192.168.xxx.xxx (192.168.xxx.xxx:21)
ftpput: cmd (null) (null)
ftpput: cmd USER xxxxx
ftpput: cmd PASS xxxx
ftpput: cmd TYPE I (null)
ftpput: cmd EPSV (null)
ftpput: can't open 'temp.jpg': No such file or directory`

**Comment by BozoTClown** [comment]
Sorry it took so long to get back to you on this, but I had to install my FTP server again as I had reinstalled the OS on my rpi. I have it working again now and the following does ftp a file from my camera to my ftp server:

/usr/bin/ftpput -v -u xxxxxxxx -p xxxxxxx -P 21 192.168.xxx.xxx test.txt

Not sure what you are trying to accomplish, but I also have a script that runs in the background that does this automatically for me.

**Comment by Morphy99** [comment]
No problem, thanks for getting back to me. It was the filename that got me. It should be source filename then destination filename. I'm guessing if you leave destination blank it keeps the same. I tried it with a an existing file and worked ok.
I'm trying to set up ftp saving of images and videos as I don't want to write to the SD card. I've tried defining it in motion.conf but it doesn't seem to be working so far. 
Not having used ftp on command line before it didn't occur that this was a simple file transfer. Not sure how you've implemented it with how motion saves images though? I'm sure it will write a temp image for mqtt snapshots for starters?

**Comment by BozoTClown** [comment]
I am not sure what your camera is like but mine has a usb port in the back of it and I save my images and stills to it, then ftp from there to my Raspberry PI.

**Comment by Morphy99** [comment]
Ah ok I didn't realise that port could be used for a usb stick! My camera is in an enclosure so I'm not sure one would fit. How did you change the save location of the temp images? And what does your ftpput script look like? I'm guessing you've put it in userscripts?

**Comment by Morphy99** [comment]
Great, thanks. I've nearly got this working however I'm getting a directory created with the date in /system/media/usb/videos so the script doesn't find anything.

I've tried removing this but didn't work either: group_date_pattern=""

**Comment by BozoTClown** [comment]
If you noticed I just search for files by extension and used a wildcard for filename.

**Comment by Morphy99** [comment]
Yea I noticed that but does it look recursively? Mine creates a folder for each date so it would need to look inside that unless I can turn that off.

**Comment by BozoTClown** [comment]
Wow, what does your motion.conf look like

**Comment by Morphy99** [comment]
What version are you running? I'm on Version: 2020-04-17T07:38:51Z ## master branch
`###################################################################
# edit this file and move it to /system/sdcard/config/motion.conf #
###################################################################

# Enable verbose debug messages to stderr
debug_msg_enable=true

# Configure the motion core parameters:

region_of_interest=300,161,1535,893
motion_sensitivity=1
motion_indicator_color=2
motion_timeout=-1
motion_detection=on
motion_tracking=off

# Configure how to deal with motion events:

motion_trigger_led=false
publish_mqtt_message=true
publish_mqtt_snapshot=false
send_email=false
send_telegram=false
telegram_alert_type=image
send_matrix=false

# General
group_date_pattern="+%Y-%m-%d"
file_date_pattern="+%d-%m-%Y_%H.%M.%S"
video_duration=20

# Record from RTSP (RTSP H264 must be enabled)
# RTSP is alternative for `record_video` function in `detectionOn.sh` - instead of 1s-getimage gets real video.
video_use_rtsp=true
video_rtsp_w=1280
video_rtsp_h=720
video_rtsp_f=15

# Snapshots
save_snapshot=false
save_snapshot_dir=/media/usb/snap
save_snapshot_attr="0666"
max_snapshot_days=20

# Videos
save_video=true
save_video_dir=/media/usb/video
save_video_attr="0666"
max_video_days=10

# Configure FTP snapshots and videos
ftp_snapshot=false
ftp_video=false
ftp_host=""
ftp_port=21
ftp_username="root"
ftp_password="libreelec"
ftp_stills_dir="snap"
ftp_videos_dir="video"

# Configure SMB snapshots and videos
smb_snapshot=false
smb_video=false
smb_share=""
smb_username=""
smb_password=""
smb_stills_path="snap"
smb_videos_path="video"
publish_mqtt_video=false
`

**Comment by BozoTClown** [comment]
There are a few differences between what you have and what I am using. I am not sure, but I think it may have something to do with this line `group_date_pattern="+%Y-%m-%d"`. You can try commenting it out and see that solves the location issue. If that doesn't work you can try to use the one I attached here. That is the one I am using.

If neither one of those does what you want. You can edit the ftp script I sent and replace the find . with find `cd /system/media/usb/videos` with `cd /system/media/usb/videos/$(date +%m%d%Y)' and the same for stills.

[motion.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/4595869/motion.zip)

**Comment by Morphy99** [comment]
I tried commenting out but it still creates a folder. I'm guessing it's a different script being run on motion.
Thanks for the date formatting, I adjusted slightly to fit what's being created '$(date +%Y-%m-%d)'

**Comment by Morphy99** [comment]
Seems there's something up with the script, I get 'find: -exec requires an argument'

**Comment by BozoTClown** [comment]
Ok for the 1st response. You need to perform house keeping so make sure yesterdays folder is empty then remove it. The command for getting yesterdays date is date -D "%s" -d $(( $(/bin/date +%s ) - 86400 )) +%Y-%m-%d

The attached file is the script I use and it works perfectly.

[ftpFiles.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/4604296/ftpFiles.zip)

**Comment by Morphy99** [comment]
Ah I see the issue, The backslash wasn't present at the end of each line in your post. I also removed the age condition for file upload and deletion as I'm triggering this script at motionoff so it should have finished recording before the script is triggered. My problem now is removing the directories created with the date. An -rf option with the date mask would work but as you can tell I'm a noob at scripting! Thanks for your help so far anyway, much appreciated. For anyone looking to use the script as I have it so far:

`#!/bin/sh

PATH=/system/sdcard/bin:/system/bin:/bin:/sbin:/usr/bin:/usr/sbin:/sbin:/bin

cd /media/usb/video/$(date +%Y-%m-%d)

/bin/find . -type f -name "*.mp4" -exec /usr/bin/ftpput -v -u xxxx -p xxxx -P 21 xxx.xxx.xxx.xxx "{}" \;

/bin/find . -type f -name "*.mp4" -exec /bin/rm "{}" \;

cd /media/usb/snap/$(date +%Y-%m-%d)

/bin/find . -type f -name "*.jpg" -exec /usr/bin/ftpput -v -u xxxx -p xxxx -P 21 xxx.xxx.xxx.xxx "{}" \;

/bin/find . -type f -name "*.jpg" -exec /bin/rm "{}" \;`

**Comment by BozoTClown** [comment]
Ok, the attached script will take care of the old files and folders. You just need to put the correct time in. I am not sure how often you are running your ftp script so adjust the minutes accordingly.
[script.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/4605845/script.zip)

**Comment by Morphy99** [comment]
Thanks this looks interesting but confusing! Can you explain what you're doing with this? What's the yesterday reference about? 
I'm not running it on a cron job, it's ran at the end of recording video once motion is detected. I tested it and it uploads the files to the root of the FTP directory still. Also the date folder isn't deleted but I'm guessing it won't do that until a day after?

**Comment by BozoTClown** [comment]
Hope this helps


[script.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/4610866/script.zip)

**Comment by Morphy99** [comment]
Thanks again. Yes it does make more sense now. I'm not sure it's working correctly however. I get the files uploaded and removed however yesterdays directory remains. I still need to figure out how to place them in separate folders on my FTP server as well? 
Probably don't need it to upload twice either? The ftppup command is on there in the new part at the top and also the original part at the bottom. I've split them into two, one to run as a cron every day at midnight, the other after recording motion.

Here's what I have tried as well your latest zip, first the cron script:

```
#!/bin/sh

PATH=/system/sdcard/bin:/system/bin:/bin:/sbin:/usr/bin:/usr/sbin:/sbin:/bin

yesterday=$(date -D "%s" -d $(( $(/bin/date +%s ) - 86400 )) +%Y-%m-%d)

if [ $(date +%H) == 0 ] && [ $(date +%M) -le 5 ]; then
   if [ -d "/media/usb/video/"$yesterday ]; then
      cd /media/usb/video
      rm -rf $yesterday
   fi

   if [ -d "/media/usb/snap/"$yesterday ]; then
      cd media/usb/snap/
      rm -rf $yesterday
   fi

fi
```
This is ok, Runs after motion but just need to add the folder on the FTP server:

```
#!/bin/sh

PATH=/system/sdcard/bin:/system/bin:/bin:/sbin:/usr/bin:/usr/sbin:/sbin:/bin

cd /media/usb/video/$(date +%Y-%m-%d)

/bin/find . -type f -name "*.mp4" -exec /usr/bin/ftpput -v -u root -p libreelec -P 21 192.168.0.5 "{}" \;

/bin/find . -type f -name "*.mp4" -exec /bin/rm "{}" \;

cd /media/usb/snap/$(date +%Y-%m-%d)

/bin/find . -type f -name "*.jpg" -exec /usr/bin/ftpput -v -u root -p libreelec -P 21 192.168.0.5 "{}" \;

/bin/find . -type f -name "*.jpg" -exec /bin/rm "{}" \;
```

**Comment by BozoTClown** [comment]
Ok, on the first script the following line is missing a /. "cd media/usb/snap/" should be "cd /media/usb/snap/". Once I fixed that it worked perfectly.

On the second script, could you write a script on the ftp server to move the files to the correct folder?

**Comment by Morphy99** [comment]
Ok I'll give that a try.
I figured out the script to upload to folders:
```
#!/bin/sh

PATH=/system/sdcard/bin:/system/bin:/bin:/sbin:/usr/bin:/usr/sbin:/sbin:/bin

cd /media/usb/video/$(date +%Y-%m-%d)

/bin/find . -type f -name "*.mp4" -exec /usr/bin/ftpput -v -u xxxx -p xxxx -P 21 xxx.xxx.xxx.xxx /video/CAM_FRONT/$(date +%Y-%m-%d.%H.%M.%S).mp4 "{}" \;

/bin/find . -type f -name "*.mp4" -exec /bin/rm "{}" \;

cd /media/usb/snap/$(date +%Y-%m-%d)

/bin/find . -type f -name "*.jpg" -exec /usr/bin/ftpput -v -u xxxx -p xxxx -P 21 xxx.xxx.xxx.xxx /snap/CAM_FRONT/$(date +%Y-%m-%d.%H.%M.%S).jpg "{}" \;

/bin/find . -type f -name "*.jpg" -exec /bin/rm "{}" \;
```

**Comment by Morphy99** [comment]
The folder cleanup script still doesn't work. I had fixed the cd /media/usb/snap part.

**Comment by BozoTClown** [comment]
Ok, I think I may have found the problem. How are you creating your cron job? I couldn't figure out how I did it, but finally came across this command and it works now. If you pipe the output of your script you are trying to run to a log file in the same folder as the script you will see if it gets created when the job runs. Mine wasn't until I ran "crontab -c /system/sdcard/config/cron/crontabs -e" command. I also mage some changes to the script since you broke them into twp scripts. Here is the one for the cron job.

`#!/bin/sh

PATH=/system/sdcard/bin:/system/bin:/bin:/sbin:/usr/bin:/usr/sbin:/sbin:/bin

yesterday=$(date -D "%s" -d $(( $(/bin/date +%s ) - 86400 )) +%Y-%m-%d)

if [ -d "/media/usb/video/$yesterday" ]; then
   rm -rf "/media/usb/video/$yesterday"
fi

if [ -d "/media/usb/snap/$yesterday" ]; then
   rm -rf "/media/usb/snap/$yesterday"
fi
`

**Comment by Morphy99** [comment]
Thanks, if you paste the code and then highlight and press <> button it will format it correctly. 
I haven't even tried running from cron yet, I was just running it manually. Is the format correct for the dir name? E.g. 2020-05-14

Another question, does your usb drive mount on boot? I've tried fstab and adding it to the end of run.sh but doesn't seem to mount. works ok manually.

**Comment by BozoTClown** [comment]
The script I pasted in my last message is the exact one I ran from cron that work. It should work manually without any issues.

I run a mount script on boot from cron that automatically mouts the USB drive.

Cron setup - `@reboot sleep 30; mount -a`

Last line of fstab - `/dev/sda1       /system/media/usb vfat  defaults,umask=000      0       0
`

``
