### ISSUE TITLE
FTP video upload fail

### ISSUE THREAD

**Issue by 0n3-70uch** [EliasKotlyar/Xiaomi-Dafang-Hacks#1199]
### Description

Hello, the detectionOn.sh script cannot upload a video via ftp.

### What did you do to debug the issue

The problems exist with the new function `$ groupname`. There is a missing mkdir function inside the  `if [ "$ftp_video" = true ]` and  `if [ "$ftp_snapshot" = true ]` loop.

### Hotfix

Remove `/$groupname` in following lines:
124, 125, 138, 151

**Comment by jmtatsch** [comment]
Should have been fixed in the last commit. Please check again and report back.

**Comment by 0n3-70uch** [comment]
I use the latest firmware 2019-10-17T19:44:04Z.
It still exists.

**Comment by jmtatsch** [comment]
with this?
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/commit/37cce787750a96b2c8a7014c6c1c40581b699bdf

**Comment by 0n3-70uch** [comment]
Yes. You can check the script. No mkdir function (only for non ftp).

**Comment by jmtatsch** [comment]
@cadavre can you please have a look?

**Comment by cadavre** [comment]
Correct. #1200 fixes this issue.

@0n3-70uch we are always open to contribution – you can always create your own PR to be a part of this community. :)

**Comment by 0n3-70uch** [comment]
> Correct. #1200 fixes this issue.
> 
> @0n3-70uch we are always open to contribution – you can always create your own PR to be a part of this community. :)

Work great now... thanks. 

I will do my best to help ;-). By the way: is there a possible solution for creating the missing folders?

**Comment by cadavre** [comment]
@0n3-70uch unfortunately not – busybox'es `ftpput` has no possibility to create directories. I ended up using SMB for long-time storage and ftp for instant-streaming to single file.

I'm looking forward to have some research on how to make instant loop recording. If I figure something out – I'll contribute for sure, but for now – I have other things on TODO.

**Comment by 0n3-70uch** [comment]
Hi, ok good to know. I will change the connection to SMB too.
