### ISSUE TITLE
SW night detection, only works while page is open

### ISSUE THREAD

**Issue by TimvdEijnden** [EliasKotlyar/Xiaomi-Dafang-Hacks#1330]
I'm configuring the SW auto night setting, but after leaving the page it doesn't work anymore.

The page states: _Please stop autonight detection service if its running._

So I stop the service. Do I have to enable it again after configuring the SW auto night setting?  

This is very unclear.

Also if you uncheck certain conditions and save and re-open the page they are checked again.

Xiaomi Xiaofang 1S 
commit sha: c2d6c41733bdc5dc8764e74bf0c96efa9ed9ee20

**Comment by Lefuneste83** [comment]
Yep I confirm the exact same behaviour on all my 3 cameras (2 Dafang and 1 Xiaofang). Tried to change the settings in different ways (SSH, UI), restarted services etc... Nothing seems to make any change to the behaviour. The cameras seem to switch properly from day to night mode immediately, but not the other way around, except when accessing the SW Night Mode page. Then it switches back instantly to Day mode, but does not turn off the IR LED.

**Comment by jmtatsch** [comment]
autonight service must be running. Likely that message is outdated.

**Comment by 0n3-70uch** [comment]
Hi, I have the same problem again. Switching to night mode is great... but in the morning nothing happend.

**Comment by so3n** [comment]
I have this exact same issue. No switching between day/night modes unless I am in the `SW night configuration` page. This is on 2 dafang devices I have

**Comment by jmtatsch** [comment]
Please post the contents of your autonight.conf.

**Comment by so3n** [comment]
```
-S -j 3 -w 3 -1 1260000 -2 90000,14,10 -3 3000,17,8
autonight_mode=sw
```

**Comment by jmtatsch** [comment]
Config file seems outdated. Delete it an let it create a new one.

**Comment by so3n** [comment]
Thanks that worked!

Out of curiosity how do I "factory reset" all the settings in case they are outdated? Or do I just delete all `*.conf` files in config folder?

**Comment by jmtatsch** [comment]
Yes, pretty much.
Even better, reformat your sd and pull a freshly checked out firmware_mod content on it.

**Comment by 0n3-70uch** [comment]
> Config file seems outdated. Delete it an let it create a new one.

Fix it for me too. Thanks

**Comment by TimvdEijnden** [comment]
I've checked my autonight.conf, this was the contents:

```
-S -j 5 -w 5 -1 1100000 -2 0,0,1 -3 0,0,1
sw_parameters='-S -j 10 -w 3 -1 850000 -2 930000,9999,10 -3 0,0,1'
autonight_mode=sw
```

I've removed autonight.conf from `/system/sdcard/config` and saved SW night changes using web interface.

Now autonight.conf contains this:
```
sw_parameters='-S -j 3 -w 3 -1 1200000 -2 930000,14,10 -3 3000,17,8'
```

Then in video configuration web page I also set it to SW again, now it contains this:
```
sw_parameters='-S -j 3 -w 3 -1 1200000 -2 930000,14,10 -3 3000,17,8'
autonight_mode=sw
```

**Comment by jmtatsch** [comment]
Well, I meant delete the conf file then reboot. But your file looks like it could work too. Does it?

**Comment by vaurdan** [comment]
I'm having this same problem with a couple Neos Smartcams. It does work for the first time (turning it on, or turning it off), but it stops working afterwards. I ran the command manually using the `autonight` binary, and it indeed detected the first change, but failed to detect the next ones.

**Comment by gadget78** [comment]
i did have this problem, it seems fixed in the beta branch :)

**Comment by adamf663** [comment]
I fixed my issue by cutting and pasting my old config params into the .dist version.
For anybody who has a Wyzecam V2, I have a tuned set of params that work much better than the 'factory default.'
I'd do a PR, but I don't now where such a document would go.

sw_parameters='-S -j 3 -w 3 -1 1280000 -2 950000,14,10 -3 3000,17,8'

I just updated three identical wyzecams to version 2.x, and they all had night mode issues with the plain autonight.conf.dist version.  They're all now doing great since I cut'n'pasted the params I had created for the defang hacks V1.

**Comment by alfatag** [comment]
I'm using a Wyzecam V2, and followed every procedure, such as deleting the file and saving to recreate a new one, running the command manually and the problem persists.

The autonight binary only detect one transition, no matter turning on or off night mode, the problem occurs in both ways.

If autonight is stuck, accessing SW night configuration page always make kind of refresh and autonight turn on or off correctly. That's 100% replicable.

ps results: /system/sdcard/bin/autonight -S -j 3 -w 3 -1 1200000 -2 930000,14,10 -3 3000,17,8

cat /system/sdcard/config/autonight.conf
sw_parameters='-S -j 3 -w 3 -1 1200000 -2 930000,14,10 -3 3000,17,8'
autonight_mode=sw

Any suggestions on what else should be done to correct this issue?

Thanks in advance!
